pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID = '084375559937'
        AWS_REGION     = 'ap-south-1'
        S3_BUCKET      = 'pinelabs-frontend'
        CLOUDFRONT_ID  = 'E29AQVB9X1DUQS'
        AWS_CREDS_ID   = 'prayog-prod-aws'
    }

    tools {
        nodejs 'node18'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Install') {
            steps {
                dir('src/frontend') {
                    sh '''
                        export HOME=$(pwd)

                        echo "Node version:"
                        node -v
                        echo "NPM version:"
                        npm -v

                        npm install
                        npm run build
                    '''
                }
            }
        }

        stage('Deploy to S3') {
            steps {
                dir('src/frontend') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                         credentialsId: AWS_CREDS_ID,
                         accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                         secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']
                    ]) {
                        sh '''
                            export AWS_DEFAULT_REGION=ap-south-1
                            echo "Deploying to S3..."
                            aws s3 sync dist/ s3://pinelabs-frontend --delete
                        '''
                    }
                }
            }
        }

        stage('Invalidate CloudFront') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding',
                     credentialsId: AWS_CREDS_ID,
                     accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                     secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']
                ]) {
                    sh '''
                        export AWS_DEFAULT_REGION=ap-south-1
                        echo "Invalidating CloudFront cache..."
                        aws cloudfront create-invalidation \
                          --distribution-id E29AQVB9X1DUQS \
                          --paths "/*"
                    '''
                }
            }
        }
    }
}
